//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarshipsOnline {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WarshipsOnline.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select color for attacked field in game:.
        /// </summary>
        internal static string AttackedFieldColor {
            get {
                return ResourceManager.GetString("AttackedFieldColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online gamemode will only be available after work on the application is completed..
        /// </summary>
        internal static string BetaVersion {
            get {
                return ResourceManager.GetString("BetaVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board size: .
        /// </summary>
        internal static string BoardSize {
            get {
                return ResourceManager.GetString("BoardSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown.
        /// </summary>
        internal static string Brown {
            get {
                return ResourceManager.GetString("Brown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change incorrect settings.
        /// </summary>
        internal static string ChangeInncorectSettings {
            get {
                return ResourceManager.GetString("ChangeInncorectSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confrim select.
        /// </summary>
        internal static string Confrim {
            get {
                return ResourceManager.GetString("Confrim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of ship locations to choose from: .
        /// </summary>
        internal static string CountShip {
            get {
                return ResourceManager.GetString("CountShip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create game.
        /// </summary>
        internal static string CreateGame {
            get {
                return ResourceManager.GetString("CreateGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game settings will not be saved. Are you sure you want to leave?.
        /// </summary>
        internal static string CreateGameExitAlert {
            get {
                return ResourceManager.GetString("CreateGameExitAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select game settings.
        /// </summary>
        internal static string CreateGameHeader {
            get {
                return ResourceManager.GetString("CreateGameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan.
        /// </summary>
        internal static string Cyan {
            get {
                return ResourceManager.GetString("Cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark blue.
        /// </summary>
        internal static string Dark_blue {
            get {
                return ResourceManager.GetString("Dark blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark cyan.
        /// </summary>
        internal static string Dark_cyan {
            get {
                return ResourceManager.GetString("Dark cyan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark gray.
        /// </summary>
        internal static string Dark_gray {
            get {
                return ResourceManager.GetString("Dark gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark green.
        /// </summary>
        internal static string Dark_green {
            get {
                return ResourceManager.GetString("Dark green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark orange.
        /// </summary>
        internal static string Dark_orange {
            get {
                return ResourceManager.GetString("Dark orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark red.
        /// </summary>
        internal static string Dark_red {
            get {
                return ResourceManager.GetString("Dark red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark violet.
        /// </summary>
        internal static string Dark_violet {
            get {
                return ResourceManager.GetString("Dark violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select color for empty enemy field in game:.
        /// </summary>
        internal static string EmptyFieldColor {
            get {
                return ResourceManager.GetString("EmptyFieldColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit warning.
        /// </summary>
        internal static string ExitAlert {
            get {
                return ResourceManager.GetString("ExitAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button colors cannot be repeated..
        /// </summary>
        internal static string ExitIncorrectSettingsAlert {
            get {
                return ResourceManager.GetString("ExitIncorrectSettingsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to menu.
        /// </summary>
        internal static string ExitSelectGamemode {
            get {
                return ResourceManager.GetString("ExitSelectGamemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        internal static string ExitSettingsAlert {
            get {
                return ResourceManager.GetString("ExitSettingsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select color for select button in game:.
        /// </summary>
        internal static string FieldSelectColor {
            get {
                return ResourceManager.GetString("FieldSelectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string FirstMenuButton {
            get {
                return ResourceManager.GetString("FirstMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        internal static string Gray {
            get {
                return ResourceManager.GetString("Gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play?.
        /// </summary>
        internal static string HowPlay {
            get {
                return ResourceManager.GetString("HowPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join game.
        /// </summary>
        internal static string JoinGame {
            get {
                return ResourceManager.GetString("JoinGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select application language:.
        /// </summary>
        internal static string LangSelect {
            get {
                return ResourceManager.GetString("LangSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marine radar.
        /// </summary>
        internal static string MarineRadar {
            get {
                return ResourceManager.GetString("MarineRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle of Warships.
        /// </summary>
        internal static string NameApplication {
            get {
                return ResourceManager.GetString("NameApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orange.
        /// </summary>
        internal static string Orange {
            get {
                return ResourceManager.GetString("Orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pink.
        /// </summary>
        internal static string Pink {
            get {
                return ResourceManager.GetString("Pink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polish.
        /// </summary>
        internal static string Polish {
            get {
                return ResourceManager.GetString("Polish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purple.
        /// </summary>
        internal static string Purple {
            get {
                return ResourceManager.GetString("Purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of round a player: .
        /// </summary>
        internal static string RoundTime {
            get {
                return ResourceManager.GetString("RoundTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea green.
        /// </summary>
        internal static string Sea_green {
            get {
                return ResourceManager.GetString("Sea green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See your board.
        /// </summary>
        internal static string SeeBoard {
            get {
                return ResourceManager.GetString("SeeBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See enemy board.
        /// </summary>
        internal static string SeePlayBoard {
            get {
                return ResourceManager.GetString("SeePlayBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select color for field selected to attack in game:.
        /// </summary>
        internal static string SelectedAttackFieldColor {
            get {
                return ResourceManager.GetString("SelectedAttackFieldColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select gamemode.
        /// </summary>
        internal static string SelectGamemode {
            get {
                return ResourceManager.GetString("SelectGamemode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select color for field of ship in game:.
        /// </summary>
        internal static string SelectShipColor {
            get {
                return ResourceManager.GetString("SelectShipColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save my changes.
        /// </summary>
        internal static string SettingsAccept {
            get {
                return ResourceManager.GetString("SettingsAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t save my changes.
        /// </summary>
        internal static string SettingsReject {
            get {
                return ResourceManager.GetString("SettingsReject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of ships per player: .
        /// </summary>
        internal static string ShipCount {
            get {
                return ResourceManager.GetString("ShipCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sky blue.
        /// </summary>
        internal static string Sky_blue {
            get {
                return ResourceManager.GetString("Sky blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use marine radar.
        /// </summary>
        internal static string UseMarineRadar {
            get {
                return ResourceManager.GetString("UseMarineRadar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Violet.
        /// </summary>
        internal static string Violet {
            get {
                return ResourceManager.GetString("Violet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game with a bot.
        /// </summary>
        internal static string WithBot {
            get {
                return ResourceManager.GetString("WithBot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local game with a second player.
        /// </summary>
        internal static string WithPlayer {
            get {
                return ResourceManager.GetString("WithPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow.
        /// </summary>
        internal static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
